# Generated by Django 3.0 on 2024-02-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentss',
            name='date',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
