# Generated by Django 3.0 on 2024-02-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_auto_20240213_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=500)),
                ('dosage', models.CharField(max_length=400)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.Booking')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.Users')),
            ],
        ),
    ]
