# Generated by Django 3.0 on 2024-02-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_remove_prescription_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prescription',
            new_name='Prescriptions',
        ),
        migrations.RenameField(
            model_name='prescriptions',
            old_name='medicinename',
            new_name='medicine_name',
        ),
    ]
