# Generated by Django 3.0 on 2024-02-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_auto_20240219_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='password123', max_length=50),
            preserve_default=False,
        ),
    ]
