# Generated by Django 3.0 on 2024-02-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_seller_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='add_image',
            field=models.ImageField(default=True, max_length=2000, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
