# Generated by Django 3.0 on 2024-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_product_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ayurvedic_properties',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
