# Generated by Django 3.0 on 2024-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_product_ayurvedic_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
