# Generated by Django 3.0 on 2024-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_auto_20240227_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_image',
            field=models.ImageField(default=True, max_length=2000, upload_to='additional_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='product_images/'),
        ),
    ]
