# Generated by Django 3.0 on 2024-02-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_auto_20240227_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
