# Generated by Django 3.0 on 2024-02-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0015_auto_20240229_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
