# Generated by Django 3.0 on 2024-03-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0018_auto_20240304_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
