# Generated by Django 3.0 on 2024-03-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0019_auto_20240304_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
