# Generated by Django 3.0 on 2024-03-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0022_auto_20240314_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
