# Generated by Django 3.0 on 2024-03-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0023_remove_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='consultation.CartItem', to='consultation.Product'),
        ),
    ]
