# Generated by Django 3.0 on 2024-04-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0031_auto_20240401_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=2000, null=True)),
                ('amt', models.CharField(max_length=225)),
                ('py_status', models.CharField(max_length=225, null=True)),
                ('P_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.P_booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.Users')),
            ],
        ),
    ]
