# Generated by Django 3.0 on 2024-04-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0032_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amt',
        ),
    ]
