# Generated by Django 3.2.22 on 2024-04-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0034_auto_20240404_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='treatments',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
