# Generated by Django 5.0.4 on 2024-04-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0039_remove_bookings_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bookingg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.bookings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.users')),
            ],
        ),
    ]
