# Generated by Django 5.0.4 on 2024-04-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0040_paymentt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paymentt',
        ),
    ]
