# Generated by Django 5.0.4 on 2024-04-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0041_bookings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Paymentt',
        ),
    ]
