# Generated by Django 5.0.4 on 2024-04-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0042_remove_bookings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentt',
            name='user',
        ),
    ]
