# Generated by Django 5.0.4 on 2024-04-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0043_remove_paymentt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentt',
            name='bookingg',
        ),
        migrations.AddField(
            model_name='paymentt',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.users'),
        ),
    ]
