# Generated by Django 5.0.4 on 2024-04-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0044_remove_paymentt_bookingg_paymentt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentt',
            name='payment_id',
        ),
    ]
