# Generated by Django 5.0.4 on 2024-04-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0045_remove_paymentt_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paymentt',
        ),
    ]
