# Generated by Django 5.0.4 on 2024-04-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0046_alter_bookings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
    ]
